plugins:
  - resolve: saber-plugin-query-posts
  
  - resolve: saber-plugin-prismjs

siteConfig:
  title: Kwin's Blog
  name: Kwin Huang
  description: 不会搞艺术的程序员不是好设计师

themeConfig:
  nav:
    - text: Blog
      link: /
    - text: Donate
      link: Donate.html
    - text: About
      link: About.html
    - text: Recommend
      link: Recommend.html
    - text: Friends
      link: Friends.html
    - text: RSS
      link: RSS.html